version: '3.8'

services:
  app:
    image: nodeimage
    container_name: nodeserver
    build: ./
    command: node server.js
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
    ports: 
      - "4000:4000"
    environment:
      - HOST=0.0.0.0
      - PORT=4000